<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns="http://www.w3.org/1999/xhtml">
<xsl:output omit-xml-declaration="no" method="xml"
	doctype-public="-//W3C//DTD XHTML 1.0 Strict//EN"
	doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd" indent="yes" encoding="UTF-8"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
				<script type="text/javascript" src="http://tablesorter.com/jquery.tablesorter.min.js"></script>
				<script type="text/javascript"><![CDATA[
					$(document).ready(function() { 
						$("#sitemap").tablesorter( { widgets: ['zebra'] } ); 
					});
				]]></script>
				<style type="text/css">
					body {
						font-family:Helvetica, Arial, sans-serif;
						font-size:13px;
						color:#545353;
					}
					table {
						border: none;
						border-collapse:collapse;
					}
					#sitemap thead tr {
						background-color:#eee;
						line-height:1.8em;
					}
					#sitemap tbody tr {
						background-color:#fcfcfc;
					}
					#sitemap tbody tr:hover {
						background-color:#ddd;
					}
					#sitemap tbody tr:hover td, #sitemap tbody tr:hover td a {
						color:#000;
					}
					#sitemap tfoot tr {
						background-color:#eee;
						line-height:1.8em;
						text-align:center;
						border-top:1px solid #444;
					}
					#content {
						margin:0 auto;
						width:1000px;
					}
					.expl {
						margin:10px 3px;
						line-height:1.3em;
					}
					.expl a {
						color:#da3114;
						font-weight:bold;
					}
					a {
						color:#000;
						text-decoration:none;
					}
					a:visited {
						color:#777;
					}
					a:hover {
						text-decoration:underline;
					}
					td {
						font-size:11px;
					}
					th {
						text-align:left;
						padding-right:30px;
						font-size:11px;
					}
					thead th {
						border-bottom:1px solid #444;
						cursor:pointer;
					}
				</style>
			</head>
			<body>
				<div id="content">
					<h1>XML Sitemap</h1>
					<p class="expl">
						Generated by <a href="http://villagedefrance.net/">Opencart Sitemap Generator</a>.
					</p>
					<p class="expl">
						You can find more information about XML sitemaps on <a href="http://sitemaps.org">sitemaps.org</a>.
					</p>
					<p class="expl">
						This sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.
					</p>			
					<table id="sitemap" cellpadding="3">
						<thead>
							<tr>
								<th width="70%">Location</th>
								<th width="10%">Last Update</th>
								<th width="10%">Frequency</th>
								<th width="5%">Priority</th>
							</tr>
						</thead>
						<tbody>
							<xsl:variable name="lower" select="'abcdefghijklmnopqrstuvwxyz'"/>
							<xsl:variable name="upper" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'"/>
							<xsl:for-each select="sitemap:urlset/sitemap:url">
								<tr>
									<td>
										<xsl:variable name="itemURL">
											<xsl:value-of select="sitemap:loc"/>
										</xsl:variable>
										<a href="{$itemURL}">
											<xsl:value-of select="sitemap:loc"/>
										</a>
									</td>
									<td>
										<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
									</td>
									<td>
										<xsl:value-of select="concat(translate(substring(sitemap:changefreq, 1, 1),concat($lower, $upper),concat($upper, $lower)),substring(sitemap:changefreq, 2))"/>
									</td>
									<td>
										<xsl:value-of select="concat(sitemap:priority*100,'%')"/>
									</td>
								</tr>
							</xsl:for-each>
						</tbody>
						<tfoot>
							<tr>
								<td colspan="4">Designed by villagedefrance - Copyright © 2013</td>
							</tr>
						</tfoot>
					</table>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>